baseURL = "https://nikhilpatidar.netlify.app"
languageCode = "en-us"
title = "Portfolio"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"

userName = "nick"
pcName = "laptop"
workDir = "mydir"
profile = "profile.txt"


ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

titleDelay = 0 # title speed : "title" in front matter
contentDelay = 0 # content speed : content in .md file


description = """
Hi I am Narayan!
I prefer to listen rather than talk, I'm less reactive, so if you think I'm ignoring you, no man, I'm an introvert.
"""


[Params.Tree]
use = true
folderName = "my_activity"
files = [ 
["Kuklink", "https://www.kuklink.net/"],
["Kuklink Bot", "https://github.com/nikhilpatidar/kuklink"],
["GitHub", "https://github.com/nikhilpatidar"],
["Buddy ❤️", "https://github.com/sumit-buddy"],
["ComputerBuddy_tg", "https://telegram.me/ComputerBuddy"],
["thetechnohack_tg", "https://telegram.me/thetechnohack"],
]


[author]
name = "Narayan"
homepage = "/"
